//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDEVIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        public int id_evaluacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string evaluacion1 { get; set; }
        public int id_indicador { get; set; }
        public string comentarios { get; set; }
        public string acciones { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string presupuesto { get; set; }
        public string producto { get; set; }
        public string dato { get; set; }
    
        public virtual Indicador Indicador { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
