//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDEVIC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class snowball_sidevicbdEntities : DbContext
    {
        public snowball_sidevicbdEntities()
            : base("name=snowball_sidevicbdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area_Cargo> Area_Cargo { get; set; }
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Eje> Eje { get; set; }
        public virtual DbSet<Evaluacion> Evaluacion { get; set; }
        public virtual DbSet<Frecuencia> Frecuencia { get; set; }
        public virtual DbSet<Indicador> Indicador { get; set; }
        public virtual DbSet<Indicador_area> Indicador_area { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Programa> Programa { get; set; }
        public virtual DbSet<Requerimientos> Requerimientos { get; set; }
        public virtual DbSet<Requerimientos_cumple> Requerimientos_cumple { get; set; }
        public virtual DbSet<Requerimientos_desempeño> Requerimientos_desempeño { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Subprograma> Subprograma { get; set; }
        public virtual DbSet<Tema> Tema { get; set; }
        public virtual DbSet<Tipo_indicador> Tipo_indicador { get; set; }
        public virtual DbSet<Tipo_presupuesto> Tipo_presupuesto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
