//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDEVIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programa()
        {
            this.Subprograma = new HashSet<Subprograma>();
        }
    
        public int id_programa { get; set; }
        public string nombre { get; set; }
        public string objetivo { get; set; }
        public string problematica { get; set; }
        public string beneficiarios { get; set; }
        public Nullable<int> id_eje { get; set; }
        public string estrategias { get; set; }
        public string lineas_accion { get; set; }
        public Nullable<int> id_area { get; set; }
        public string presupuesto { get; set; }
        public string porcentaje_1 { get; set; }
        public string procentaje_2 { get; set; }
        public string procentaje_3 { get; set; }
        public string procentaje_4 { get; set; }
        public Nullable<int> id_tipo_presupuesto { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Eje Eje { get; set; }
        public virtual Tipo_presupuesto Tipo_presupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subprograma> Subprograma { get; set; }
    }
}
